@sequential
"get up"
"stand up"
@sequential3D
"get up"
"stand up"
  "stand up"
  "for your right"
  "don't give up", "the fight"
@sequentialNatives
"string"
42
3.14
yes
no
nil
@associative
who: "let the dogs out"
theAnswerToLifeTheUniverseAndEverything: 42
@associative3D
this: 
  is: 
    pretty: 
      high: "doe"
@associativeNatives
string: "string"
int: 42
float: 3.14
true: yes
false: no
null: nil